### PR TITLE
Feat/create hoomd sim

### LINKED ISSUE #2: drop cme_utils as requirement
we only use cme_utils for:

 `from cme_utils.manip.ff_from_foyer import set_coeffs` which should be replaced by `foyer.Forcefield.apply` 

and `from cme_utils.manip.convert_rigid import init_wrapper`. Not sure what to do about this one, but it'll need updating I assume.

### LINKED ISSUE #4: switch from using init.hoomdxml to create_hoomd_sim
hoomdxml is deprecated, so let's update!

### PR DESCRIPTION
**Pull request by jennyfothergill**
Started updating planckton to use `create_hoomd_sim` and foyer's `Forcefield.apply()`. Right now this PR breaks ~e_factor and~ rigid bodies!

Tests pass locally, but we should test that we get the same result before and after this change. 

fixes #4, fixes #2

### CODE REVIEW

**Comment by chrisjonesBSU** [comment]
I feel like this PR would be a good opportunity to also address #5 

I think the Simulation class could contain different methods based on if the user wants a quenched simulation at a single temp, or an annealed simulation over a range of temps.

**Comment by jennyfothergill** [comment]
OK I think I've fixed e_factor with the new api, but I still need to work on rigid bodies.

@chrisjonesBSU I think a temperature ramp would be great, but I'd like to keep this PR small. So I won't try to add it in as well.

**Comment by chrisjonesBSU** [comment]
One thought I have, is that it may be easier to scale the LJ values before all of the pairs are created in hoomd. Instead, couldn't we iterate through `self.system` which I believe is a parmed structure and scale any of the LJ values by the e_factor.  

In other words, we might not have to use the `set_coeffs` util and iterate through `ljtypes`.  

Also, possibly related, I don't see where the renaming atom type step in `init.py` would still be needed if we are using `create_hoomd_sim` and just passing in the typed parmed structure.

**Comment by jennyfothergill** [comment]
> One thought I have, is that it may be easier to scale the LJ values before all of the pairs are created in hoomd. Instead, couldn't we iterate through `self.system` which I believe is a parmed structure and scale any of the LJ values by the e_factor.
> 
> In other words, we might not have to use the `set_coeffs` util and iterate through `ljtypes`.

good point! I will look into this. I will compare the two using timeit. We may even be able to modify the forcefield object. 🤔 

> Also, possibly related, I don't see where the renaming atom type step in init.py would still be needed if we are using create_hoomd_sim and just passing in the typed parmed structure.

another good point cx I just didn't even think to change it

**Comment by mikemhenry** [comment]
Since rigid bodies might be tough to figure out, do we want to merge this without rigid body support or do we want to wait until rigid bodies are working?

**Comment by jennyfothergill** [comment]
OK, I've got rigid bodies working, and now I'm thinking about how to integrate this with planckton, here are some thoughts:
- I don't think I necessarily want to have users have to type their compound before putting it into planckton. I'd like to continue to support use with the typed mol2 files we already have though? not sure.
- At the very least I'd like to use these files to verify that the typing with gaff does what we expect. Maybe would be a good unit test
- I'd like to move away from using bespoke forcefields in planckton. let's use gaffoyer and oplsaa through foyer.
- I'm not sure how continue supporting the old way of doing rigid bodies... I'd like to chat about how bad it would be to just remove/replace with new way (i.e. autodetect rings and set as rigid)

**Comment by jennyfothergill** [comment]
OK tests are passing locally, next step I want to add testing for using rigid bodies.

**Comment by chrisjonesBSU** [comment]
A couple things that came to mind:

1. Should the default behavior be to set `assert_angles` and `assert_dihedrals` to `False`? I feel like it would be important to know/have feedback if your system's angles and dihedrals aren't fully paramaterized.  One thing we talked about was added a `foyer_kwargs` parameter to the init function.  If we're using rigid bodies, then it may be the case that there are angles and dihedrals that aren't paramaterized, but it won't matter if they are part of a structure being set to rigid anyway.  

2. It looks like we are still using parmed to calculate the mass of a molecule.  This might be another place where the ele package can be implemented.

**Comment by jennyfothergill** [comment]
These are both great suggestions. I think it will be best to address them in separate PRs:

> 1. Should the default behavior be to set `assert_angles` and `assert_dihedrals` to `False`? I feel like it would be important to know/have feedback if your system's angles and dihedrals aren't fully paramaterized.  One thing we talked about was added a `foyer_kwargs` parameter to the init function.  If we're using rigid bodies, then it may be the case that there are angles and dihedrals that aren't parameterized, but it won't matter if they are part of a structure being set to rigid anyway.

This PR is to retain the current behavior of planckton with the hoomd 2 api. Right now all the tests are using the built in opv-gaff forcefield, but I think eventually we should switch to gaff and oplsaa from foyer. At that point it would be good to make sure that all our compounds are parameterized correctly and add any missing types to foyer/gaff.
 
> 2. It looks like we are still using parmed to calculate the mass of a molecule.  This might be another place where the ele package can be implemented.

It's definitely on the todo list: #6 c: this PR is just taking me a while.

**Comment by jennyfothergill** [comment]
> Since rigid bodies might be tough to figure out, do we want to merge this without rigid body support or do we want to wait until rigid bodies are working?

ugh I'm still stuck on rigid bodies, so yeah probably. I will work on getting this working without rigid bodies for now.

**Comment by jennyfothergill** [comment]
OK, this is ready for review. Rigid bodies are not supported. ~The reason that codecov is failing is because we aren't testing load from smiles, and we can't test that without using gafffoyer or oplsaa. I'd prefer to add those in a separate PR.~ 
I added a test for loading a compound from smiles, but we can't test running a sim from smiles with gaff until we add gaffoyer to the image.

**Comment by chrisjonesBSU** [comment]
I think that assert_angles and assert_dihedrals should default to True, just because it would be useful to know before a simulation starts what/how many angles and dihedrals aren't being accounted for. Maybe we can add a `foyer_kwargs` parameter to the init function if the user wants to override that and set these to false.

Also, I think the e_factor implementation would also work if we iterate through the particles in the parmed structure and multiply their epsilon values by e_factor. I'm not sure if this is necessarily faster than the current implementation iterating through the hoomd pair objects and using the `set_coeffs` function, but I think it is definitely a lot simpler to read and understand.

**Comment by jennyfothergill** [comment]
>I think that assert_angles and assert_dihedrals should default to True, just because it would be useful to know before a simulation starts what/how many angles and dihedrals aren't being accounted for. Maybe we can add a foyer_kwargs parameter to the init function if the user wants to override that and set these to false.

good point! Having a the fact that dihedrals are not parameterized buried in the code is not great. I have added an option for users to raise an error if the dihedrals are missing (pass `foyer_kwargs={}` to `Pack`) and started an issue to look into what's missing #30

**Comment by jennyfothergill** [comment]
>Also, I think the e_factor implementation would also work if we iterate through the particles in the parmed structure and multiply their epsilon values by e_factor. I'm not sure if this is necessarily faster than the current implementation iterating through the hoomd pair objects and using the set_coeffs function, but I think it is definitely a lot simpler to read and understand.

compared the timing of using the set_coeffs function to looping through the parmed structure and set_coeffs is marginally faster--
```
for atom in system.atoms:
    atom.epsilon *= e_factor
```
748 µs ± 26.9 µs
```
e_factor = 2
with sim:
    if e_factor != 1:                                              
        logging.info("Scaling LJ coeffs by e_factor")                   
        hoomd.util.quiet_status()                                       
        # catch all instances of LJ pair  
        ljtypes = [                                                     
            i                                                           
            for i in sim.forces                                         
            if isinstance(i, hoomd.md.pair.lj)                          
            or isinstance(i, hoomd.md.special_pair.lj)                  
        ]                                                               
                                                                        
        for lj in ljtypes:                                              
            pair_list = lj.get_metadata()["pair_coeff"].get_metadata()  
            for pair_dict in pair_list:                                 
                # Scale the epsilon values by e_factor                  
                try:                                                    
                    a, b, new_dict = set_coeffs(                        
                        pair_dict, e_factor                        
                    )                                                   
                    lj.pair_coeff.set(a, b, **new_dict)                 
                except ValueError:                                      
                    # if the pair has not been defined,                 
                    # it will not have a dictionary object              
                    # instead it will be a string (e.g. "ca-ca")        
                    # and will fail when trying to make the new_dict  
                    pass                                                
        hoomd.util.unquiet_status() 
```
689 µs ± 37.5 µs

using a system of 2 16mer p3ht

**Comment by jennyfothergill** [comment]
One last thing before this is merged-- I don't see [`shrink factor`](https://github.com/cmelab/planckton/pull/14/files#diff-bdb93b6cf98d22f040ad2f25744deb360a22dc81d6abeb970ec1c9a50d26bd98R36) used anywhere in the code. Is this a mistake? Where should it be used?

**Pull request merged**
