### PR TITLE
Remove cmeutils from requirements

### LINKED ISSUE #2: drop cme_utils as requirement
we only use cme_utils for:

 `from cme_utils.manip.ff_from_foyer import set_coeffs` which should be replaced by `foyer.Forcefield.apply` 

and `from cme_utils.manip.convert_rigid import init_wrapper`. Not sure what to do about this one, but it'll need updating I assume.

### PR DESCRIPTION
**Pull request by jennyfothergill**
Fixes #2. 
* copied over files from cme_utils
* also deleted old circleci workflow
* tests pass locally

### CODE REVIEW

**Comment by jennyfothergill** [comment]
accidentally based this on the feat/unyt branch, oops

**Comment by jennyfothergill** [comment]
I think this PR will be made unnecessary by #14 ...

**Review by mikemhenry — COMMENTED** [review]
There is a lot going on in this PR other than what was said at the start, does it need to be based off of a different branch? While PR #14 might make this one unnecessary, that PR might take awhile to finish.

**Comment by jennyfothergill** [comment]
handled by #14

**Pull request closed without merging**
