### PR TITLE
Fully support loading a compound from SMILES and outside forcefields

### LINKED ISSUE #26: Move away from using custom forcefields
-Add support for gafffoyer
-Add support for oplsaa

### LINKED ISSUE #43: Initialize from smiles

### PR DESCRIPTION
**Pull request by jennyfothergill**
fixes #43 fixes #26 

- Before this, load from smiles was supported but the only forcefields included were the custom ffs, so there was little guarantee that they would work. 
- We should check that our custom compounds end up with the same types as their smiles+gafffoyer counterparts.

### CODE REVIEW

**Comment by chrisjonesBSU** [comment]
The tests are failing for me, and I think it's related to GAFF-foyer defaulting to using the `.xml` that has no SMARTS def.

```
        if self.atomTypeDefinitions == {}:
>           raise FoyerError('Attempting to atom-type using a force field '
                    'with no atom type defitions.')
E           foyer.exceptions.FoyerError: Attempting to atom-type using a force field with no atom type defitions
```

I had the same issue [ Foyer defaults to using the gaff_nosmartsdefs.xml #10 ](https://github.com/rsdefever/GAFF-foyer/issues/10)

Also, I think both tests in `test_sim` are using the default of `remove_hydrogens = False`, these should also be tested with removing hydrogens.  Also, I think that using the non-custom force fields along with a UA system may introduce some potential issues, because in this case we can't use SMARTS matching (I think?)

**Comment by jennyfothergill** [comment]
>The tests are failing for me, and I think it's related to GAFF-foyer defaulting to using the .xml that has no SMARTS def.

I think this is my bad actually, the container rebuild can't be triggered by the PR, so I need to update the container on master.

**Comment by chrisjonesBSU** [comment]
> > The tests are failing for me, and I think it's related to GAFF-foyer defaulting to using the .xml that has no SMARTS def.
> 
> I think this is my bad actually, the container rebuild can't be triggered by the PR, so I need to update the container on master.

The error message I showed came up when I ran it locally, and I think it's different than the test failing in the container run?  

EDIT: Nvm..I went and checked again and it looks like the same one.

**Comment by jennyfothergill** [comment]
> > > The tests are failing for me, and I think it's related to GAFF-foyer defaulting to using the .xml that has no SMARTS def.
> > 
> > 
> > I think this is my bad actually, the container rebuild can't be triggered by the PR, so I need to update the container on master.
> 
> The error message I showed came up when I ran it locally, and I think it's different than the test failing in the container run?
> 
> EDIT: Nvm..I went and checked again and it looks like the same one.

Hmmm, that's odd. All the tests pass locally for me. Maybe we're running into an issue between mac and linux? I definitely think you're onto something because the tests are still failing. In the issue you posted, Ryan recommends using only antefoyer. Does that fix it for you?

EDIT: yeah, we're getting a new error that seems to match your "missing smarts def" issue -- I think the failed to find `load_GAFF()` was my bad, but this is new.
```
>           raise FoyerError('Attempting to atom-type using a force field '
                    'with no atom type defitions.')
E           foyer.exceptions.FoyerError: Attempting to atom-type using a force field with no atom type defitions.
```

**Review by chrisjonesBSU — APPROVED** [review]

**Pull request merged**
